name: retrace
version: 1.1.0
description: Regenerates minified stacktraces.
author: Bj√∂rn Melinder <bjorn.melinder@gmail.com>
homepage: https://github.com/bjornm/retrace
dependencies:
  args: ">=0.13.0 <0.14.0"
  source_maps: ">=0.10.0+1 <1.0.0"
dev_dependencies:
  test: any
  guinness2: "^0.0.3"
executables:
  retrace:
